export const commonMedicationNames = [
  "Amoxicilina",
  "Azitromicina",
  "Captopril",
  "Cefalexina",
  "Clonazepam",
  "Dipirona",
  "Enalapril",
  "Hidroxizina",
  "Ibuprofeno",
  "Insulina",
  "Losartana",
  "Metformina",
  "Nimesulida",
  "Omeprazol",
  "Paracetamol",
  "Prednisona",
  "Salbutamol",
  "Sertralina",
  "Sinvastatina",
  "Vitamina D",
];
